name: Node.js CI

on:
  push:

jobs:
  nodeci:
    env: 
      CI: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.5]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g npm
      - run: npm ci
      - run: npm run build
      - run: npm run test
