name: Tests CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  runNpmTarget:
    name: Run NPM target
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run NPM target
        uses: anna-money/github-actions-npm@v2
